language: r
cache: packages
pandoc_version: 1.19.2.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
GITHUB_PAT=3fbf2f724d00207bcb389913e0d0974f3a270b54:
  secure: Ghsa7D+XHNNH1ZxdXUEjnx04aQNFRNzMPgLZwqomnweYhhNnNkk6msfkCKVPkz5vVoCX0nbPVoBD1YD+jX/LTktiIKzpsVsd5z6fcs8UrudYdnuKm81QEv74CsRQwf06vDEBYXKHyLlFS9UmSmR4UgzEJmO8Xwx6e+6hinCZbpEu9+7q80I1QCQ14jD34UKeDAIF3brdiK62JXIFo6JCD75G/MopHShQJ7RyXDV6kR1Q5t7wyn3IFdQzTWHZFuwi/TnyKj3DSMbbn2iNttcYkt2zX6S23BKGa4ePtJzW84JxrYrdlz28/OVm/so+8YrlyeZ1fMhHpDtdEoj5sGG+iZd/jYpKLwi/z/IH4Hu3K4xNnJP3OqHLeRajRlHgUup0/5w6R02KXlhRGb4v9VY2MAIv/kC8EHgGca/9w4RH5lzf3WF0offO3f3N94kDZedymsTQILZkKEkkD2xifFHDLc9xjAQkgfKl8E2NiLfa6H1qfRT7v9qXx6vDjWLQ99NvsnJX6C0Ugb9xGF/M8pABVrdIW8RE/qoDK5CBm7QiGQDgKc5I+9ZHmyLTXbC3hVlUz+MRcJKPtng0526UfHFd3gmOj0aGfmSXwXZbHvQYSoMDNnaLN57l6qnSRZ4cPk32fgiyQxfaAShnKgcqmDADvnKUm3A5ou72EFQeQxdFBlM=
